<?php
function TanggalIndo($tanggal)
{
	$bulan = array ('Januari',
				'Februari',
				'Maret',
				'April',
				'Mei',
				'Juni',
				'Juli',
				'Agustus',
				'September',
				'Oktober',
				'November',
				'Desember'
			);
	$split = explode('-', $tanggal);
	return $split[2] . ' ' . $bulan[ (int)$split[1]-1 ] . ' ' . $split[0];
};
function namahari($tanggal){
    
    //fungsi mencari namahari
    //format $tgl YYYY-MM-DD
    //harviacode.com
    
    $tgl=substr($tanggal,8,2);
    $bln=substr($tanggal,5,2);
    $thn=substr($tanggal,0,4);

    $info=date('w', mktime(0,0,0,$bln,$tgl,$thn));
    
    switch($info){
        case '0': return "Minggu"; break;
        case '1': return "Senin"; break;
        case '2': return "Selasa"; break;
        case '3': return "Rabu"; break;
        case '4': return "Kamis"; break;
        case '5': return "Jumat"; break;
        case '6': return "Sabtu"; break;
    };
    
};
 include 'fpdf/fpdf.php';
 include 'exfpdf.php';
 include 'easyTable.php';
 include '../../inc/db_connect.php';
 $bulan1 = array ('Januari',
				'Februari',
				'Maret',
				'April',
				'Mei',
				'Juni',
				'Juli',
				'Agustus',
				'September',
				'Oktober',
				'November',
				'Desember'
			);
	$bulan=isset($_GET['bulanku']) ? $_GET['bulanku'] : '';
	$tahun=isset($_GET['tahunku']) ? $_GET['tahunku'] : '';
	$tapel=isset($_GET['tapel']) ? $_GET['tapel'] : '';
	$pdf=new exFPDF('L','mm',array(330,240));
	$pdf->AddPage(); 
	$pdf->SetFont('helvetica','',8);
	$table2=new easyTable($pdf, '{37,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,2,5,30,8,8,8,8,8,8,8,8}');
	$table2->easyCell('LAPORAN BULANAN SEKOLAH DASAR (DAFTAR 1)','colspan:27;border:LTR;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('TAHUN PELAJARAN '.$tapel,'colspan:27;border:LR;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('BULAN : '.$bulan1[(int)$bulan-1].' '.$tahun,'colspan:27;border:LBR;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('Nama Sekolah','border:L;align:L;font-style:B');
	$table2->easyCell(': SD ISLAM AL-JANNAH','colspan:5;align:L;font-style:B');
	$table2->easyCell('Alamat','colspan:10;border:R;align:L;font-style:B');
	$table2->easyCell('','border:R;align:L;font-style:B');
	$table2->easyCell('A. TANAH','colspan:2;rowspan:3;border:RB;align:L;font-style:B');
	$table2->easyCell('Luas (m2)','colspan:4;border:RB;align:C;font-style:B');
	$table2->easyCell('Tahun Pembelian','colspan:2;rowspan:2;border:RB;align:C;font-style:B;font-size:7');
	$table2->easyCell('Harga (Rp.)','colspan:2;rowspan:2;border:RB;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('Tahun Pendirian','border:L;align:L;font-style:B');
	$table2->easyCell(': 2007','colspan:5;align:L;font-style:B');
	$table2->easyCell('Jalan/No. Telp.','colspan:4;align:L;font-style:B');
	$table2->easyCell(': Jl. Raya Gabuswetan No. 1','colspan:6;border:R;align:L;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('Darat/Sawah','colspan:2;border:RB;align:C;font-style:B;font-size:6');
	$table2->easyCell('No. Persil','colspan:2;border:RB;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('NSS/NSB','border:L;align:L;font-style:B');
	$table2->easyCell(': 102021803031','colspan:5;align:L;font-style:B');
	$table2->easyCell('Desa/Kelurahan','colspan:4;align:L;font-style:B');
	$table2->easyCell(': Gabuswetan','colspan:6;border:R;align:L;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('3.111','colspan:2;border:RB;align:C;font-style:B');
	$table2->easyCell('956','colspan:2;border:RB;align:C;font-style:B');
	$table2->easyCell('1996','colspan:2;border:RB;align:C;font-style:B');
	$table2->easyCell('22.500.00','colspan:2;border:RB;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('NPSN','border:L;align:L;font-style:B');
	$table2->easyCell(': 20258088','colspan:5;align:L;font-style:B');
	$table2->easyCell('Kategori','colspan:4;align:L;font-style:B');
	$table2->easyCell(': Non IDT','colspan:6;border:R;align:L;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('B. BANGUNAN/RUANG','colspan:2;rowspan:3;border:RB;align:L;font-style:B');
	$table2->easyCell('Baik','colspan:2;border:RB;align:C;font-style:B');
	$table2->easyCell('Sedang','colspan:2;border:RB;align:C;font-style:B');
	$table2->easyCell('Rusak','colspan:2;border:RB;align:C;font-style:B');
	$table2->easyCell('Jumlah','colspan:2;border:RB;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('Status','border:L;align:L;font-style:B');
	$table2->easyCell(': Swasta','colspan:5;align:L;font-style:B');
	$table2->easyCell('Kecamatan','colspan:4;align:L;font-style:B');
	$table2->easyCell(': Gabuswetan','colspan:6;border:R;align:L;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('Bgn','border:RB;align:C;font-style:B');
	$table2->easyCell('Rng','border:RB;align:C;font-style:B');
	$table2->easyCell('Bgn','border:RB;align:C;font-style:B');
	$table2->easyCell('Rng','border:RB;align:C;font-style:B');
	$table2->easyCell('Bgn','border:RB;align:C;font-style:B');
	$table2->easyCell('Rng','border:RB;align:C;font-style:B');
	$table2->easyCell('Bgn','border:RB;align:C;font-style:B');
	$table2->easyCell('Rng','border:RB;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('','border:LB;align:L;font-style:B');
	$table2->easyCell('','colspan:5;border:B;align:L;font-style:B');
	$table2->easyCell('Kabupaten/Provinsi','colspan:4;align:L;border:B;font-style:B');
	$table2->easyCell(': Indramayu/Jawa Barat','colspan:6;border:RB;align:L;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('1','border:RB;align:C;font-style:B');
	$table2->easyCell('12','border:RB;align:C;font-style:B');
	$table2->easyCell('','border:RB;align:C;font-style:B');
	$table2->easyCell('','border:RB;align:C;font-style:B');
	$table2->easyCell('','border:RB;align:C;font-style:B');
	$table2->easyCell('','border:RB;align:C;font-style:B');
	$table2->easyCell('','border:RB;align:C;font-style:B');
	$table2->easyCell('','border:RB;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('BANYAKNYA MURID','rowspan:3;border:LRBT;align:C;font-style:B');
	$table2->easyCell('I','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('II','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('III','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('IV','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('V','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('VI','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('Jumlah','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('Jumlah Semua','rowspan:3;border:LRBT;align:C;font-style:B;font-size:6');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('C. MENYEWA per Bulan Rp. - / MENUMPANG di SD .......','rowspan:2;colspan:10;border:LRBT;align:L;font-style:B');
	$table2->printRow();
	$table2->easyCell('2 Bag','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('2 Bag','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('2 Bag','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('2 Bag','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('2 Bag','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('2 Bag','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('12 Bag','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('D','border:LRBT;align:L;font-style:B');
	$table2->easyCell('JENIS/SIFAT BANGUNAN (P:Permanen; SP:Semi-Permanen; Dr:Darurat)','colspan:9;border:LRBT;align:L;font-style:B;font-size:7');
	$table2->printRow();
	$table2->easyCell('Jumlah Bulan Lalu','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('','colspan:2;rowspan:2;border:LRBT;align:L;font-style:B;font-size:6');
	$table2->easyCell('P','rowspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('SP','rowspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('Dr','rowspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('Th. Pendirian','colspan:3;border:LRBT;align:C;font-style:B');
	$table2->easyCell('Harga (Rp.)','colspan:2;rowspan:2;border:LRBT;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('Keluar dalam Bulan ini','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('SP','border:LRBT;align:C;font-style:B');
	$table2->easyCell('Dr','border:LRBT;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('Masuk dalam Bulan ini','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('a.','border:LRBT;align:L;font-style:B');
	$table2->easyCell('Bangunan Sekolah','border:LRBT;align:L;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('2007','border:LRBT;align:C;font-style:B;font-size:6');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('600.000.000','colspan:2;border:LRBT;align:C;font-style:B;font-size:6');
	$table2->printRow();
	$table2->easyCell('Jumlah Penghabisan','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('b.','border:LRBT;align:L;font-style:B');
	$table2->easyCell('Madrasah','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B;font-size:6');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B;font-size:6');
	$table2->printRow();
	$table2->easyCell('Jumlah dalam Bulan ini','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('c.','border:LRBT;align:L;font-style:B');
	$table2->easyCell('Rumah Dinas','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B;font-size:6');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B;font-size:6');
	$table2->printRow();
	$table2->easyCell('','colspan:16;border:LBT;align:L;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:L;font-style:B');
	$table2->easyCell('1. Kepala Sekolah','border:LRBT;align:L;font-style:B;font-size:7');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B;font-size:6');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B;font-size:6');
	$table2->printRow();
	$table2->easyCell('BANYAKNYA MURID MENURUT UMUR','rowspan:3;border:LRBT;align:C;font-style:B');
	$table2->easyCell('I','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('II','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('III','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('IV','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('V','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('VI','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('Jumlah','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('Jumlah Semua','rowspan:3;border:LRBT;align:C;font-style:B;font-size:6');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('','border:RB;align:C;font-style:B');
	$table2->easyCell('2. Guru','border:LRBT;align:L;font-style:B;font-size:7');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B;font-size:6');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B;font-size:6');
	$table2->printRow();
	$table2->easyCell('2 Bag','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('2 Bag','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('2 Bag','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('2 Bag','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('2 Bag','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('2 Bag','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('12 Bag','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('','border:RB;align:C;font-style:B');
	$table2->easyCell('3. Penjaga Sekolah','border:LRBT;align:L;font-style:B;font-size:7');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B;font-size:6');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B;font-size:6');
	$table2->printRow();
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('d.','border:RB;align:C;font-style:B');
	$table2->easyCell('Lain-lain','border:LRBT;align:L;font-style:B;font-size:7');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B;font-size:6');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B;font-size:6');
	$table2->printRow();
	$table2->easyCell('5 Tahun <','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('E. PENYEDIAAN AIR BERSIH : POMPA','colspan:10;border:LRBT;align:L;font-style:B');
	$table2->printRow();
	$table2->easyCell('6 Tahun','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('F','border:LRBT;align:L;font-style:B');
	$table2->easyCell('PERKAKAS','border:LRBT;align:L;font-style:B');
	$table2->easyCell('Baik','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('Sedang','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('Rusak','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('Jumlah','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('7 Tahun','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:L;font-style:B');
	$table2->easyCell('1. Bangku','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('8 Tahun','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:L;font-style:B');
	$table2->easyCell('2. Meja Murid','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('9 Tahun','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:L;font-style:B');
	$table2->easyCell('3. Kursi Murid','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('10 Tahun','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:L;font-style:B');
	$table2->easyCell('4. Lemari','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('11 Tahun','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:L;font-style:B');
	$table2->easyCell('5. Meja Guru','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('12 Tahun','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:L;font-style:B');
	$table2->easyCell('6. Kursi Guru','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('13 Tahun >','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:L;font-style:B');
	$table2->easyCell('7. Papan Tulis','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('Jumlah','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:L;font-style:B');
	$table2->easyCell('8. Kursi Tamu','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('','colspan:16;border:LBT;align:L;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:L;font-style:B');
	$table2->easyCell('9. Rak Buku','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('BANYAKNYA MURID MENURUT AGAMA','rowspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('ISLAM','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('ISLAM','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('ISLAM','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('ISLAM','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('ISLAM','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('ISLAM','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('ISLAM','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('Jumlah Semua','rowspan:2;border:LRBT;align:C;font-style:B;font-size:6');
	$table2->easyCell('','border:R;align:L;font-style:B');
	$table2->easyCell('G','rowspan:2;border:LRBT;align:L;font-style:B');
	$table2->easyCell('JUMLAH GURU','rowspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('Kepsek','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('Guru Kelas','colspan:2;border:LRBT;align:C;font-style:B;font-size:7');
	$table2->easyCell('PAI','border:LRBT;align:C;font-style:B');
	$table2->easyCell('OR','border:LRBT;align:C;font-style:B');
	$table2->easyCell('TU','border:LRBT;align:C;font-style:B');
	$table2->easyCell('Jml','border:LRBT;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('L','border:LRBT;align:C;font-style:B');
	$table2->easyCell('P','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:L;font-style:B');
	$table2->easyCell('1','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('21','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('1','border:LRBT;align:C;font-style:B');
	$table2->easyCell('1','border:LRBT;align:C;font-style:B');
	$table2->easyCell('3','border:LRBT;align:C;font-style:B');
	$table2->easyCell('27','border:LRBT;align:C;font-style:B');
	$table2->printRow();
	$table2->easyCell('Jumlah Bulan Lalu','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('H','align:L;font-style:B');
	$table2->easyCell('JUMLAH HARI EFEKTIF','colspan:2;align:L;font-style:B');
	$table2->easyCell('21','align:R;font-style:B');
	$table2->easyCell('HARI','colspan:6;border:R;align:L;font-style:B');
	$table2->printRow();
	$table2->easyCell('Keluar dalam Bulan Ini','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('I','align:L;font-style:B');
	$table2->easyCell('ABSENSI','colspan:2;align:L;font-style:B');
	$table2->easyCell('Sakit','colspan:2;align:R;font-style:B');
	$table2->easyCell(':','align:L;font-style:B');
	$table2->easyCell('61','align:R;font-style:B');
	$table2->easyCell('Siswa','colspan:3;border:R;align:L;font-style:B');
	$table2->printRow();
	$table2->easyCell('Masuk dalam Bulan Ini','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('','align:L;font-style:B');
	$table2->easyCell('113 Siswa','colspan:2;align:L;font-style:B');
	$table2->easyCell('Izin','colspan:2;align:R;font-style:B');
	$table2->easyCell(':','align:L;font-style:B');
	$table2->easyCell('51','align:R;font-style:B');
	$table2->easyCell('Siswa','colspan:3;border:R;align:L;font-style:B');
	$table2->printRow();
	$table2->easyCell('Jumlah Penghabisan','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('','align:L;font-style:B');
	$table2->easyCell('% Kehadiran : 1,74%','colspan:2;align:L;font-style:B');
	$table2->easyCell('Lain-lain','colspan:2;align:R;font-style:B');
	$table2->easyCell(':','align:L;font-style:B');
	$table2->easyCell('1','align:R;font-style:B');
	$table2->easyCell('Siswa','colspan:3;border:R;align:L;font-style:B');
	$table2->printRow();
	$table2->easyCell('Jumlah dalam Bulan ini','border:LRBT;align:L;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','colspan:2;border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:LRBT;align:C;font-style:B');
	$table2->easyCell('','border:R;align:C;font-style:B');
	$table2->easyCell('','colspan:10;border:BR;align:L;font-style:B');
	$table2->printRow();
	$table2->endTable();
	$pdf->Output();



 

?>